/* Generated By:JavaCC: Do not edit this line. JustGrammarConstants.java */
package at.grisa.just;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JustGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAMSTART = 5;
  /** RegularExpression Id. */
  int TYPEVOID = 6;
  /** RegularExpression Id. */
  int TYPEINTEGER = 7;
  /** RegularExpression Id. */
  int TYPEBOOLEAN = 8;
  /** RegularExpression Id. */
  int BYREF = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int DECIMALPOINT = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int SCOPEBEGIN = 21;
  /** RegularExpression Id. */
  int SCOPEEND = 22;
  /** RegularExpression Id. */
  int INSTRUCTIONEND = 23;
  /** RegularExpression Id. */
  int ALLOCATION = 24;
  /** RegularExpression Id. */
  int OPENBRACE = 25;
  /** RegularExpression Id. */
  int CLOSEBRACE = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int EQUALS = 30;
  /** RegularExpression Id. */
  int EQUALSNOT = 31;
  /** RegularExpression Id. */
  int LESSTHAN = 32;
  /** RegularExpression Id. */
  int LESSTHANEQUALS = 33;
  /** RegularExpression Id. */
  int GREATERTHAN = 34;
  /** RegularExpression Id. */
  int GREATERTHANEQUALS = 35;
  /** RegularExpression Id. */
  int PLUS = 36;
  /** RegularExpression Id. */
  int MINUS = 37;
  /** RegularExpression Id. */
  int MULTIPLY = 38;
  /** RegularExpression Id. */
  int DIVIDE = 39;
  /** RegularExpression Id. */
  int NOT = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"program\"",
    "\"void\"",
    "\"int\"",
    "\"boolean\"",
    "\"byref\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "<LETTER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "\".\"",
    "<NUMBER>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
  };

}
